In [2]:
import numpy as np

## Data types and attributes

In [3]:
# main data type is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([
    [1, 2, 3.3],
    [4, 5, 6.5]
])
a3 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ],
    [
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]
    ]
])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.shape

(3,)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

## Create DataFrame from NumPy array

In [14]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating arrays

In [15]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
type(ones)

numpy.ndarray

In [17]:
zeroes = np.zeros((2, 3))
zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
range_array = np.arange(0, 10)
range_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 6, 9, 7, 6],
       [0, 6, 7, 6, 0],
       [5, 9, 0, 7, 7]])

In [22]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.05869513, 0.24586126, 0.78296122],
       [0.71142859, 0.51542035, 0.27130404],
       [0.09742788, 0.76591787, 0.25998682],
       [0.39713964, 0.40664566, 0.52976355],
       [0.26933101, 0.34753916, 0.79190441]])

In [24]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.22242489, 0.4448413 , 0.07599113],
       [0.43478302, 0.42581181, 0.16876818],
       [0.83439675, 0.84622617, 0.1775476 ],
       [0.0559498 , 0.19648319, 0.80409101],
       [0.01226872, 0.46949547, 0.1549511 ]])

## Random seed

In [46]:
np.random.seed(5)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[3, 6, 6],
       [0, 9, 8],
       [4, 7, 0],
       [0, 7, 1],
       [5, 7, 0]])

In [60]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [32]:
random_array_4.shape

(5, 3)

In [59]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [62]:
a1[0]

np.int64(1)

In [63]:
a2[0]

array([1. , 2. , 3.3])

In [66]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [71]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])

In [73]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [74]:
# get the first 3 numbers of the inner most arrays
a4[:, :, :, :3]

array([[[[0, 5, 3],
         [7, 1, 8],
         [0, 2, 0],
         [2, 9, 9]],

        [[0, 0, 9],
         [5, 3, 2],
         [8, 7, 1],
         [3, 6, 7]],

        [[2, 7, 0],
         [8, 2, 0],
         [0, 9, 0],
         [5, 1, 4]]],


       [[[2, 0, 3],
         [3, 7, 1],
         [4, 6, 1],
         [0, 1, 8]],

        [[6, 8, 5],
         [7, 4, 1],
         [5, 2, 9],
         [5, 7, 7]],

        [[6, 0, 6],
         [2, 6, 8],
         [5, 8, 9],
         [6, 2, 5]]]])

## Manipulating and comparing arrays

### Arithmetic

In [75]:
a1

array([1, 2, 3])

In [76]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [78]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [79]:
a1 * ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [80]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [83]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [84]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [94]:
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [95]:
a2.reshape(2, 3, 1) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [96]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [97]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [100]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [101]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

## Aggregation

In [103]:
built_in_list = [1, 2, 3]
type(built_in_list)

list

In [104]:
sum(built_in_list)

6

In [105]:
sum(a1)

np.int64(6)

In [106]:
np.sum(a1)

np.int64(6)

In [107]:
massive_array = np.random.random(100000)
massive_array[:10]

array([0.76108474, 0.18802993, 0.30765459, 0.24639364, 0.59604912,
       0.09190485, 0.89560999, 0.46227594, 0.44481236, 0.1047113 ])

In [108]:
%timeit sum(massive_array) # python built-in

3.77 ms ± 63.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [109]:
%timeit np.sum(massive_array)

14.1 μs ± 76.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [114]:
np.mean(a2)

np.float64(3.6333333333333333)

In [ ]:
np.std(a2)

np.float64(1.8226964152656422)

In [ ]:
np.var(a2)

np.float64(3.3222222222222224)

## Reshape and transpose

In [119]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [120]:
a2.shape

(2, 3)

In [121]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [122]:
a3.shape

(2, 3, 3)

In [123]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [124]:
a2.reshape(2, 3, 1) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [127]:
a2.transpose()

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [128]:
a2.transpose().shape

(3, 2)

In [129]:
a3.transpose()

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

## Dot product

In [131]:
np.random.seed(88)
mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1, mat2

(array([[8, 0, 1],
        [4, 5, 1],
        [0, 5, 0],
        [2, 1, 4],
        [7, 9, 7]]),
 array([[7, 6, 6],
        [3, 1, 0],
        [8, 6, 0],
        [0, 5, 7],
        [5, 3, 9]]))

In [132]:
# element-wise
mat1 * mat2

array([[56,  0,  6],
       [12,  5,  0],
       [ 0, 30,  0],
       [ 0,  5, 28],
       [35, 27, 63]])

In [134]:
# dot product
np.dot(mat1, mat2.transpose())

array([[ 62,  24,  64,   7,  49],
       [ 64,  17,  62,  32,  44],
       [ 30,   5,  30,  25,  15],
       [ 44,   7,  22,  33,  49],
       [145,  30, 110,  94, 125]])

## Nut butter sales

In [135]:
np.random.seed(88)
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

array([[ 0, 15, 17],
       [10,  5,  1],
       [16,  5, 12],
       [16,  2,  1],
       [11,  4,  7]])

In [136]:
# weekly sales dataframe
weekly_sales = pd.DataFrame(
    sales_amounts,
    index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
    columns=["Almond butter", "Peanut butter", "Cashew butter"]
)
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon                0             15             17
Tues              10              5              1
Wed               16              5             12
Thurs             16              2              1
Fri               11              4              7

In [141]:
prices = np.array([10, 8, 2])
prices

array([10,  8,  2])

In [150]:
butter_prices = pd.DataFrame(prices.reshape(1, 3), columns=["Almond butter", "Peanut butter", "Cashew butter"], index=["Price"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8              2

In [153]:
total_sales = prices.dot(sales_amounts.T)
total_sales

array([154, 142, 224, 178, 156])

In [159]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

Mon  Tues  Wed  Thurs  Fri
Price  154   142  224    178  156

In [160]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon                0             15             17        154
Tues              10              5              1        142
Wed               16              5             12        224
Thurs             16              2              1        178
Fri               11              4              7        156

## Comparison

In [161]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [162]:
a1 >= a2

array([[ True,  True, False],
       [False, False, False]])

In [163]:
a1 > 5

array([False, False, False])

In [164]:
a1 < 5

array([ True,  True,  True])

In [165]:
a1 == a1

array([ True,  True,  True])

In [166]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

## Sorting

In [167]:
random_array

array([[9, 6, 9, 7, 6],
       [0, 6, 7, 6, 0],
       [5, 9, 0, 7, 7]])

In [168]:
np.sort(random_array)

array([[6, 6, 7, 9, 9],
       [0, 0, 6, 6, 7],
       [0, 5, 7, 7, 9]])

In [170]:
np.argsort(random_array)

array([[1, 4, 3, 0, 2],
       [0, 4, 1, 3, 2],
       [2, 0, 3, 4, 1]])

In [171]:
a1

array([1, 2, 3])

In [172]:
np.argsort(a1)

array([0, 1, 2])

In [173]:
np.argmin(a1)

np.int64(0)

In [174]:
np.argmax(a1)

np.int64(2)

In [176]:
random_array

array([[9, 6, 9, 7, 6],
       [0, 6, 7, 6, 0],
       [5, 9, 0, 7, 7]])

In [178]:
np.argmax(random_array, axis=1)

array([0, 2, 1])

In [ ]:
np.argmax(random_array, axis=0)


array([0, 2, 0, 0, 2])

# Practical

<img src="images/panda.png">

In [182]:
# turn image in numpy array
from matplotlib.image import imread

panda_data = imread("images/panda.png")
type(panda_data)

numpy.ndarray

In [184]:
panda_data

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [185]:
panda_data.size

24465000

In [186]:
panda_data.ndim

3

In [187]:
panda_data.shape

(2330, 3500, 3)

In [188]:
panda_data[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png">

In [189]:
car_data = imread("images/car-photo.png")

In [191]:
car_data[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]],
      shape=(1, 575, 4), dtype=float32)